services:

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro # first docker login - then mount config.json into Watchtower
    environment:
      - DOCKER_CONFIG=/
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300 # Check for updates every 5 minutes
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_TRACE=true
